In [1]:
import numpy as np
import sklearn
import pandas as pd

In [2]:
df = pd.read_csv('./data/aden.csv',sep=';')

In [7]:
max_quinzaine=24

In [4]:
df['area'] = df.apply(lambda row: str(row['lat_area'])+'_'+str(row['lon_area']), axis=1)

# Creation d'une matrice

In [23]:
dfAgregateTotal=df.groupby(['Annee (0)','quinzaine_week','area']).agg(['count'])
dfAgregateTotal

                               Unnamed: 0 jour (0) mois (0)  \
                                    count    count    count
Annee (0) quinzaine_week area
2008      3              38_34          2        2        2
                         55_64          1        1        1
                         5_14           1        1        1
                         8_14           1        1        1
          5              24_45          1        1        1
                         55_64          1        1        1
                         5_15           1        1        1
          6              37_35          1        1        1
                         38_32          1        1        1
                         40_33          1        1        1
                         55_64          1        1        1
                         8_13           1        1        1
          7              39_32          1        1        1
                         40_31          1        1        1
                         41_30          1        1        1
                         5_14           1        1        1
          8              16_30          1        1        1
                         38_30          1        1        1
                         38_31          1        1        1
                         40_32          1        1        1
                         48_68          1        1        1
                         5_14           1        1        1
          9              18_35          1        1        1
          10             20_26          1        1        1
                         38_30          1        1        1
                         38_33          1        1        1
                         39_28          1        1        1
                         39_30          1        1        1
                         39_33          1        1        1
                         40_33          1        1        1
...                                   ...      ...      ...
2013      13             38_20          1        1        1
          14             39_20          1        1        1
                         55_64          1        1        1
          19             24_36          1        1        1
          20             55_64          2        2        2
          21             4_29           1        1        1
                         7_27           1        1        1
          22             54_64          2        2        2
          23             38_28          2        2        2
                         55_64          1        1        1
2014      2              42_39          1        1        1
                         5_14           1        1        1
          3              18_23          1        1        1
                         37_21          1        1        1
          5              33_74          1        1        1
                         40_37          1        1        1
          6              39_20          1        1        1
                         61_43          1        1        1
          7              37_21          1        1        1
                         38_21          1        1        1
                         40_41          1        1        1
          8              33_74          1        1        1
                         37_21          1        1        1
          13             55_64          2        2        2
          16             38_20          1        1        1
          17             55_64          1        1        1
          18             55_64          2        2        2
                         61_43          1        1        1
          19             55_64          1        1        1
          24             42_18          1        1        1

                               dist �� la c̫te (nq)  zone lat (0) long(0)  \
                                              count count   count   count
Annee (0) quinzaine_week area
2008      3              38_34                    0     2       2       2
                         55_64                    0     1       1       1
                         5_14                     0     1       1       1
                         8_14                     0     1       1       1
          5              24_45                    0     1       1       1
                         55_64                    0     1       1       1
                         5_15                     0     1       1       1
          6              37_35                    0     1       1       1
                         38_32                    0     1       1       1
                         40_33                    0     1       1       1
                         55_64                    0     1       1       1
                         8_13                     0     1       1       1
          7              39_32                    0     1       1       1
                         40_31                    0     1       1       1
                         41_30                    0     1       1       1
                         5_14                     0     1       1       1
          8              16_30                    0     1       1       1
                         38_30                    0     1       1       1
                         38_31                    0     1       1       1
                         40_32                    0     1       1       1
                         48_68                    0     1       1       1
                         5_14                     0     1       1       1
          9              18_35                    0     1       1       1
          10             20_26                    0     1       1       1
                         38_30                    0     1       1       1
                         38_33                    0     1       1       1
                         39_28                    0     1       1       1
                         39_30                    0     1       1       1
                         39_33                    0     1       1       1
                         40_33                    0     1       1       1
...                                             ...   ...     ...     ...
2013      13             38_20                    0     1       1       1
          14             39_20                    0     1       1       1
                         55_64                    0     1       1       1
          19             24_36                    0     1       1       1
          20             55_64                    0     2       2       2
          21             4_29                     0     1       1       1
                         7_27                     0     1       1       1
          22             54_64                    0     2       2       2
          23             38_28                    0     2       2       2
                         55_64                    0     1       1       1
2014      2              42_39                    0     1       1       1
                         5_14                     0     1       1       1
          3              18_23                    0     1       1       1
                         37_21                    0     1       1       1
          5              33_74                    0     1       1       1
                         40_37                    0     1       1       1
          6              39_20                    0     1       1       1
                         61_43                    0     1       1       1
          7              37_21                    0     1       1       1
                         38_21                    0     1       1       1
                         40_41                    0     1       1       1
          8              33_74                    0     1       1       1
                         37_21                    0     1       1       1
          13             55_64                    0     2       2       2
          16             38_20                    0     1       1       1
          17             55_64                    0     1       1       1
          18             55_64                    0     2       2       2
                         61_43                    0     1       1       1
          19             55_64                    0     1       1       1
          24             42_18                    0     1       1       1

                               type(0) pavillon statut de l'attaque(0)  \
                                 count    count                  count
Annee (0) quinzaine_week area
2008      3              38_34       2        2                      2
                         55_64       1        1                      1
                         5_14        1        1                      1
                         8_14        1        1                      1
          5              24_45       1        1                      1
                         55_64       1        1                      1
                         5_15        1        1                      1
          6              37_35       1        1                      1
                         38_32       1        1                      1
                         40_33       1        1                      1
                         55_64       1        1                      1
                         8_13        1        1                      1
          7              39_32       1        1                      1
                         40_31       1        1                      1
                         41_30       1        1                      1
                         5_14        1        1                      1
          8              16_30       1        1                      1
                         38_30       1        1                      1
                         38_31       1        1                      1
                         40_32       1        1                      1
                         48_68       1        1                      1
                         5_14        1        1                      1
          9              18_35       1        1                      1
          10             20_26       1        1                      1
                         38_30       1        1                      1
                         38_33       1        1                      1
                         39_28       1        1                      1
                         39_30       1        1                      1
                         39_33       1        1                      1
                         40_33       1        1                      1
...                                ...      ...                    ...
2013      13             38_20       1        1                      1
          14             39_20       1        1                      1
                         55_64       1        1                      1
          19             24_36       1        1                      1
          20             55_64       2        2                      2
          21             4_29        1        1                      1
                         7_27        1        1                      1
          22             54_64       2        2                      2
          23             38_28       2        2                      2
                         55_64       1        1                      1
2014      2              42_39       1        1                      1
                         5_14        1        1                      1
          3              18_23       1        1                      1
                         37_21       1        1                      1
          5              33_74       1        1                      1
                         40_37       1        1                      1
          6              39_20       1        1                      1
                         61_43       1        1                      1
          7              37_21       1        1                      1
                         38_21       1        1                      1
                         40_41       1        1                      1
          8              33_74       1        1                      1
                         37_21       1        1                      1
          13             55_64       2        2                      2
          16             38_20       1        1                      1
          17             55_64       1        1                      1
          18             55_64       2        2                      2
                         61_43       1        1                      1
          19             55_64       1        1                      1
          24             42_18       1        1                      1

                                 ...    bless̩es  meurtre Knives    RPG  \
                                 ...       count    count   count count
Annee (0) quinzaine_week area    ...
2008      3              38_34   ...           0        0       0     0
                         55_64   ...           0        0       0     0
                         5_14    ...           0        0       0     0
                         8_14    ...           0        0       0     0
          5              24_45   ...           0        0       0     0
                         55_64   ...           0        0       0     0
                         5_15    ...           0        0       0     0
          6              37_35   ...           0        0       0     0
                         38_32   ...           0        0       0     0
                         40_33   ...           0        0       0     0
                         55_64   ...           0        0       0     0
                         8_13    ...           0        0       0     0
          7              39_32   ...           0        0       0     0
                         40_31   ...           0        0       0     0
                         41_30   ...           0        0       0     0
                         5_14    ...           0        0       0     0
          8              16_30   ...           0        0       0     0
                         38_30   ...           0        0       0     0
                         38_31   ...           0        0       0     0
                         40_32   ...           0        0       0     0
                         48_68   ...           0        0       0     0
                         5_14    ...           0        0       0     0
          9              18_35   ...           0        0       0     0
          10             20_26   ...           0        0       0     0
                         38_30   ...           0        0       0     0
                         38_33   ...           0        0       0     0
                         39_28   ...           0        0       0     0
                         39_30   ...           0        0       0     0
                         39_33   ...           0        0       0     0
                         40_33   ...           0        0       0     0
...                              ...         ...      ...     ...   ...
2013      13             38_20   ...           0        0       0     0
          14             39_20   ...           0        0       0     0
                         55_64   ...           0        0       0     0
          19             24_36   ...           0        0       0     0
          20             55_64   ...           0        0       0     0
          21             4_29    ...           0        0       0     0
                         7_27    ...           0        0       0     0
          22             54_64   ...           0        0       0     0
          23             38_28   ...           0        0       0     0
                         55_64   ...           0        0       0     0
2014      2              42_39   ...           0        0       0     0
                         5_14    ...           0        0       0     0
          3              18_23   ...           0        0       0     0
                         37_21   ...           0        0       0     0
          5              33_74   ...           0        0       0     0
                         40_37   ...           0        0       0     0
          6              39_20   ...           0        0       0     0
                         61_43   ...           0        0       0     0
          7              37_21   ...           0        0       0     0
                         38_21   ...           0        0       0     0
                         40_41   ...           0        0       0     0
          8              33_74   ...           0        0       0     0
                         37_21   ...           0        0       0     0
          13             55_64   ...           0        0       0     0
          16             38_20   ...           0        0       0     0
          17             55_64   ...           0        0       0     0
          18             55_64   ...           0        0       0     0
                         61_43   ...           0        0       0     0
          19             55_64   ...           0        0       0     0
          24             42_18   ...           0        0       0     0

                               descriptif latitude longitude  \
                                    count    count     count
Annee (0) quinzaine_week area
2008      3              38_34          2        2         2
                         55_64          1        1         1
                         5_14           1        1         1
                         8_14           1        1         1
          5              24_45          1        1         1
                         55_64          1        1         1
                         5_15           1        1         1
          6              37_35          1        1         1
                         38_32          1        1         1
                         40_33          1        1         1
                         55_64          1        1         1
                         8_13           1        1         1
          7              39_32          1        1         1
                         40_31          1        1         1
                         41_30          1        1         1
                         5_14           1        1         1
          8              16_30          1        1         1
                         38_30          1        1         1
                         38_31          1        1         1
                         40_32          1        1         1
                         48_68          1        1         1
                         5_14           1        1         1
          9              18_35          1        1         1
          10             20_26          1        1         1
                         38_30          1        1         1
                         38_33          1        1         1
                         39_28          1        1         1
                         39_30          1        1         1
                         39_33          1        1         1
                         40_33          1        1         1
...                                   ...      ...       ...
2013      13             38_20          1        1         1
          14             39_20          1        1         1
                         55_64          1        1         1
          19             24_36          1        1         1
          20             55_64          2        2         2

In [55]:
dfAgregate=dfAgregateTotal[dfAgregateTotal.columns[1]].to_frame()

In [59]:
#print type(dfAgregate)
df2=dfAgregate[dfAgregateTotal.columns[1]]
print df2
print list(df2.columns.values)

Annee (0)  quinzaine_week  area
2008       3               38_34    2
                           55_64    1
                           5_14     1
                           8_14     1
           5               24_45    1
                           55_64    1
                           5_15     1
           6               37_35    1
                           38_32    1
                           40_33    1
                           55_64    1
                           8_13     1
           7               39_32    1
                           40_31    1
                           41_30    1
                           5_14     1
           8               16_30    1
                           38_30    1
                           38_31    1
                           40_32    1
                           48_68    1
                           5_14     1
           9               18_35    1
           10              20_26    1
                           38_30    1
                           38_33    1
                           39_28    1
                           39_30    1
                           39_33    1
                           40_33    1
                                   ..
2013       13              38_20    1
           14              39_20    1
                           55_64    1
           19              24_36    1
           20              55_64    2
           21              4_29     1
                           7_27     1
           22              54_64    2
           23              38_28    2
                           55_64    1
2014       2               42_39    1
                           5_14     1
           3               18_23    1
                           37_21    1
           5               33_74    1
                           40_37    1
           6               39_20    1
                           61_43    1
           7               37_21    1
                           38_21    1
                           40_41    1
           8               33_74    1
                           37_21    1
           13              55_64    2
           16              38_20    1
           17              55_64    1
           18              55_64    2
                           61_43    1
           19              55_64    1
           24              42_18    1
Name: (jour (0), count), dtype: int64

AttributeError: 'Series' object has no attribute 'columns'

# On créé un nouveau dataframe

Le nouveau dataframe:
    1. years
    2. area
    3. quinzaine_week